---
# Lab Environment Inventory
# Azure-based lab DCs (DC01 and DC02)
# Domain: linkedin.local

all:
  children:
    lab:
      children:
        # Lab Domain Controllers (Azure VMs)
        lab_domain:
          hosts:
            dc01.linkedin.local:
              ansible_host: "{{ vault_dc01_ip }}"
              ansible_user: "{{ vault_dc01_user }}"
              ansible_password: "{{ vault_dc01_password }}"
              domain_name: "linkedin.local"
              ad_site_name: "Default-First-Site-Name"
              primary_dc_ip: "10.0.0.6"
              primary_dc_hostname: "dc01.linkedin.local"
              private_ip: "10.0.0.6"
              public_ip: "{{ vault_dc01_ip }}"
              vm_name: "DC01"
              resource_group: "VAMDEVTEST"
            
            dc02.linkedin.local:
              ansible_host: "{{ vault_dc02_ip }}"
              ansible_user: "{{ vault_dc02_user }}"
              ansible_password: "{{ vault_dc02_password }}"
              domain_name: "linkedin.local"
              ad_site_name: "Default-First-Site-Name"
              primary_dc_ip: "10.0.0.6"  # DC01 is primary
              primary_dc_hostname: "dc01.linkedin.local"
              private_ip: "10.1.0.6"
              public_ip: "{{ vault_dc02_ip }}"
              vm_name: "DC02"
              resource_group: "VAMDEVTEST"

  vars:
    # WinRM connection settings for Azure lab VMs
    ansible_connection: winrm
    ansible_port: 5985  # HTTP (use 5986 for HTTPS)
    ansible_winrm_transport: ntlm  # Use NTLM for lab (not domain-joined)
    ansible_winrm_server_cert_validation: ignore
    
    # Lab domain credentials
    domain_admin_user: "{{ vault_lab_domain_admin }}"
    domain_admin_password: "{{ vault_lab_domain_password }}"
    dsrm_password: "{{ vault_lab_dsrm_password }}"
    
    # Environment marker
    deployment_environment: "lab"
    
    # Lab-specific paths (using C: drive for lab)
    adds_database_path: "C:\\Windows\\NTDS"
    adds_sysvol_path: "C:\\Windows\\SYSVOL"
    adds_log_path: "C:\\Windows\\NTDS\\Logs"
    
    # Install options
    install_dns: true
    is_global_catalog: true
    read_only_dc: false
    
    # Azure-specific settings
    azure_subscription_id: "81adc0ae-0abb-443d-9b8b-05cb650a2d46"
    azure_resource_group: "VAMDEVTEST"
    azure_location: "uksouth"
